spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/instagram?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: woyaojiankang321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true